<?php

namespace AppBundle\Repository;

/**
 * CartProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
