# src/AppBundle/Resources/config/services.yml
services:
    repo.promotions:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - \AppBundle\Entity\Promotion
    promotion_manager:
        class: AppBundle\Service\PromotionManager
        arguments: ['@repo.promotions']
    price_calculator:
        class: AppBundle\Service\PriceCalculator
        arguments: ['@promotion_manager']

    type.product_type:
        class: AppBundle\Form\ProjectType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }